### ISSUE TITLE
certificate chain validation error message is not returned

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-core-go#117]
The error message for validate certificate is not returned. [Here is code](https://github.com/notaryproject/notation-core-go/blob/0cb6e7508c67ee9a3b3a2e680ae7841ec37fdd32/x509/cert_validations.go#L92).

https://github.com/notaryproject/notation-core-go/blob/0cb6e7508c67ee9a3b3a2e680ae7841ec37fdd32/x509/cert_validations.go#L91-L94

The `subject.CheckSignatureFrom` may return an error and the error message is not returned, which will finally cause an inaccurate error.

**Comment by patrickzheng200** [comment]
I will take this one and go through notation-core-go for similar issues.
