### ISSUE TITLE
error message may not right

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-core-go#119]
In line 67 of the [code](https://github.com/notaryproject/notation-core-go/blob/0cb6e7508c67ee9a3b3a2e680ae7841ec37fdd32/x509/cert_validations.go#L67), if i == 0 which is the leaf cert, the error message still says that it is the intermediate certificate, so the error message may not right. It may need to return the CommonName of the cert to help use identify the invalid cert.

https://github.com/notaryproject/notation-core-go/blob/0cb6e7508c67ee9a3b3a2e680ae7841ec37fdd32/x509/cert_validations.go#L56-L78

**Comment by patrickzheng200** [comment]
Nice catch. And instead of the `CommonName`, we could show the `Subject` of the cert.
