### ISSUE TITLE
self-signed leaf cert error message not clear

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-core-go#121]
https://github.com/notaryproject/notation-core-go/blob/0cb6e7508c67ee9a3b3a2e680ae7841ec37fdd32/x509/cert_validations.go#L43-L54
In line 50 or 53, if it return an error, it had better tell user that there is only one cert and the cert subject is xxxxx with error:xxxx
Also, it may be replaced by `isSelfSigned()` because it also need to make sure that the issuer and subject are the same.

**Comment by patrickzheng200** [comment]
The fix will be included in PR 120 as well.
