### ISSUE TITLE
[revocation] Implement OCSP support

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation-core-go#124]
Spec: https://github.com/notaryproject/notaryproject/blob/main/specs/trust-store-trust-policy.md#ocsp

**Comment by kody-kimberl** [comment]
Proposed design: https://github.com/notaryproject/notation-core-go/issues/132

**Comment by yizha1** [comment]
@priteshbandi @kody-kimberl Can we close this issue since PR were merged

**Comment by yizha1** [comment]
Closed as OCSP was implemented and released.
