### ISSUE TITLE
self-signed leaf cert validation issue

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-core-go#126]
We didn’t check the issuer of the self-signed leaf certificate. The self-signed leaf certificate should also be self-issued.
https://github.com/notaryproject/notation-core-go/blob/d336b6a8e953cfe7139234a70a167f883d573bae/x509/cert_validations.go#L46-L58

**Comment by yizha1** [comment]
@JeyJeyGao is this still a valid issue?

**Comment by JeyJeyGao** [comment]
We can close it now.

**Comment by JeyJeyGao** [comment]
As discussed yesterday, this is a bug and should be fixed.
