### ISSUE TITLE
Temporarily bypassing status check for #135

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-core-go#136]
The PR #135 is to shift the golang support window to `[1.19, 1.20]`. Although we've got sufficient approvals, we are not able to merged PR since the check for `golang 1.18` is removed, which is intended.

<img width="687" alt="image" src="https://user-images.githubusercontent.com/32161882/229681709-4144a67d-9a91-4cf7-b90a-89457121ea51.png">

To merge the PR, we need to temporarily uncheck the "Do not allow bypassing the above settings" for the `main` branch to bypass the build check.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/32161882/229681864-b5482581-6a88-4485-a487-a2ae443b9d11.png">

Of course, it is also can be done by unchecking "Require branches to be up to date before merging" but I think unchecking the "Do not allow bypassing the above settings" is safer.

@notaryproject/notaryproject-notation-core-go-maintainers Please reply `LGTM` to proceed or comment for suggestions.

**Comment by toddysm** [comment]
LGTM

**Comment by yizha1** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by SteveLasker** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by shizhMSFT** [comment]
Merged #135 using the proposed method.
