### ISSUE TITLE
Reducing the PR approval count to 2

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notation-core-go#137]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

To increase the velocity of the development, we would like to reduce the PR approval count to 2. The justification is the following: with the current count of 3 approvals we have 4 people who need to be involved in the PR. Our initial goal was to have min 3. By reducing to 2 approvals required we still have 3 people including the original submitter.

### What did you expect to happen?

Reduce PR approvals to 2

### How can we reproduce it?

N/A

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

N/A

**Comment by shizhMSFT** [comment]
We can keep the original count of 3 approvals for `notation-core-go` since it is a crypto critical library.

**Comment by yizha1** [comment]
Close this issue. We keep 3 approvals as @shizhMSFT explained
