### ISSUE TITLE
Release v1.0.0-rc.3 for notation-core-go

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation-core-go#142]
Release `v1.0.0-rc.3` for `notation-core-go`:

- [x] Decide on main commit for a release: Commit id [4d6ef22](https://github.com/notaryproject/notation-core-go/commit/4d6ef22973c589936fa0546c54e61a18c0a1c1c0)
- [x] Cut branch named `v1.0.0-rc.3` based on agreed upon main commit
- [x] Cut a tag named `v1.0.0-rc.3`

Looking for LGTM @iamsamirzon  @vaninrao10 @priteshbandi  @toddysm @FeynmanZhou @shizhMSFT @patrickzheng200 @JeyJeyGao @rgnote @gokarnm @SteveLasker @NiazFK @justincormack

**Comment by patrickzheng200** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by FeynmanZhou** [comment]
LGTM

**Comment by yizha1** [comment]
Closed as released https://github.com/notaryproject/notation-core-go/releases/tag/v1.0.0-rc.3
