### ISSUE TITLE
vote: tag 1.0.0

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-core-go#157]
## Release

This would mean tagging 0c1ec3be33eb1d3cfc9770f9abc86176ee4fb7e9 as `v1.0.0` to release.

## Vote

We need at least `4` approvals from `6` maintainers to release `notation-core-go v1.0.0`.

- [x] Junjie Gao (@JeyJeyGao)
- [x] Milind Gokarn (@gokarnm)
- [x] Patrick Zheng (@Two-Hearts)
- [x] Pritesh Bandi (@priteshbandi)
- [ ] Rakesh Gariganti (@rgnote)
- [x] Shiwei Zhang (@shizhMSFT)

## Changes

The code changes compared to `v1.0.0-rc.4` include:

- #133
- #151
- #154
- #153
- #156

**Full Changelog**: https://github.com/notaryproject/notation-core-go/compare/v1.0.0-rc.4...0c1ec3be33eb1d3cfc9770f9abc86176ee4fb7e9 

## Action Requested

Please respond LGTM or REJECT (with reasoning).

**Comment by Two-Hearts** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by gokarnm** [comment]
LGTM

**Comment by shizhMSFT** [comment]
Released [v1.0.0](https://github.com/notaryproject/notation-core-go/releases/tag/v1.0.0)
