### ISSUE TITLE
vote: tag 1.0.1

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-core-go#168]
## Release

This would mean tagging c834adcaa9683e3e9f2086a6a0ac3e73ad318bec as `v1.0.1` to release.

## Vote

We need at least `4` approvals from `6` maintainers to release `notation-core-go v1.0.1`.

- [x] Junjie Gao (@JeyJeyGao)
- [ ] Milind Gokarn (@gokarnm)
- [x] Patrick Zheng (@Two-Hearts)
- [x] Pritesh Bandi (@priteshbandi)
- [ ] Rakesh Gariganti (@rgnote)
- [x] Shiwei Zhang (@shizhMSFT)

## Changes

The code changes compared to `v1.0.0` include:

- #162
- #160
- #163
- #167
- #169

**Full Changelog**: https://github.com/notaryproject/notation-core-go/compare/v1.0.0...c834adcaa9683e3e9f2086a6a0ac3e73ad318bec

## Action Requested

Please respond LGTM or REJECT (with reasoning).

**Comment by Two-Hearts** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by yizha1** [comment]
I strongly suggest including the fix of this issue https://github.com/notaryproject/notation-core-go/issues/164. Users reported this when they configured the wrong key usage, the error message was a bit misleading. But if we cannot meet the target date of the overall [Notation 1.0.1 release plan](https://github.com/notaryproject/notation/issues/804), this issue will not block.

**Comment by shizhMSFT** [comment]
If #164 can be resolved in time, we can restart the voting process.

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by shizhMSFT** [comment]
I've updated description to c834adcaa9683e3e9f2086a6a0ac3e73ad318bec so that #169 is included. Thus, the voting process is reset.

**Comment by Two-Hearts** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by shizhMSFT** [comment]
Closing as [`v1.0.1`](https://github.com/notaryproject/notation-core-go/releases/tag/v1.0.1) has been released.
