### ISSUE TITLE
vote: tag 1.0.2

### ISSUE THREAD

**Issue by Two-Hearts** [notaryproject/notation-core-go#187]
## Release

This would mean tagging 2bc927beb626d46bb434215af243d49d629b13d8 as `v1.0.2` to release.

## Vote

We need at least `4` approvals from `6` maintainers to release `notation-core-go v1.0.2`.

- [x] Junjie Gao (@JeyJeyGao)
- [ ] Milind Gokarn (@gokarnm)
- [x] Patrick Zheng (@Two-Hearts)
- [x] Pritesh Bandi (@priteshbandi)
- [ ] Rakesh Gariganti (@rgnote)
- [x] Shiwei Zhang (@shizhMSFT)

## Changes
The code changes compared to v1.0.1 include:
* fix: fix license dependency check workflow by @Two-Hearts in https://github.com/notaryproject/notation-core-go/pull/170
* build(deps): bump golang.org/x/crypto from 0.14.0 to 0.15.0 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/172
* doc: update README to align with the new project brand by @FeynmanZhou in https://github.com/notaryproject/notation-core-go/pull/158
* chore: invalid signing time prompt improvement by @fanndu in https://github.com/notaryproject/notation-core-go/pull/173
* build(deps): bump golang.org/x/crypto from 0.15.0 to 0.16.0 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/175
* build(deps): bump actions/setup-go from 4 to 5 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/177
* build(deps): bump golang.org/x/crypto from 0.16.0 to 0.17.0 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/180
* build(deps): bump github/codeql-action from 2 to 3 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/179
* Updated the maintainers and codeowners files by @toddysm in https://github.com/notaryproject/notation-core-go/pull/183
* build(deps): bump golang.org/x/crypto from 0.17.0 to 0.18.0 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/184

**Full Changelog**: https://github.com/notaryproject/notation-core-go/compare/v1.0.1...2bc927beb626d46bb434215af243d49d629b13d8

## Action Requested

Please respond LGTM or REJECT (with reasoning).

**Comment by shizhMSFT** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by Two-Hearts** [comment]
Closing as [v1.0.2](https://github.com/notaryproject/notation-core-go/releases/tag/v1.0.2) has been released.
