### ISSUE TITLE
vote: tag v1.0.3

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation-core-go#205]
## Release

This would mean tagging 4211b09afe43a31a8609ebb3f8ae6fdbba41fadc as `v1.0.3` to release.

## Vote

We need at least `4` approvals from `6` maintainers to release `notation-core-go v1.0.3`.

- [x] Junjie Gao (@JeyJeyGao)
- [ ] Milind Gokarn (@gokarnm)
- [x] Patrick Zheng (@Two-Hearts)
- [x] Pritesh Bandi (@priteshbandi)
- [ ] Rakesh Gariganti (@rgnote)
- [x] Shiwei Zhang (@shizhMSFT)

## Changes
The code changes compared to v1.0.2 include:
* build(deps): bump codecov/codecov-action from 3 to 4 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/188
* build(deps): bump github.com/fxamacker/cbor/v2 from 2.5.0 to 2.6.0 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/190
* build(deps): bump golang.org/x/crypto from 0.18.0 to 0.21.0 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/193
* chore: add GitHub action for stale issues and PRs by @yizha1 in https://github.com/notaryproject/notation-core-go/pull/174
* bump: bump up golang version to v1.21 by @Two-Hearts in https://github.com/notaryproject/notation-core-go/pull/194
* chore: org maintainers update by @toddysm in https://github.com/notaryproject/notation-core-go/pull/196
* fix(ci): update codecov token by @JeyJeyGao in https://github.com/notaryproject/notation-core-go/pull/199
* fix: leaf certificate validation by @Two-Hearts in https://github.com/notaryproject/notation-core-go/pull/202
* build(deps): bump golang.org/x/crypto from 0.21.0 to 0.22.0 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/200
* build(deps): bump apache/skywalking-eyes from a790ab8dd23a7f861c18bd6aaa9b012e3a234bce to cd7b195c51fd3d6ad52afceb760719ddc6b3ee91 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/197
* build(deps): bump actions/stale from 8 to 9 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/195
* build(deps): bump golang.org/x/crypto from 0.22.0 to 0.23.0 by @dependabot in https://github.com/notaryproject/notation-core-go/pull/204

**Full Changelog**: https://github.com/notaryproject/notation-core-go/compare/v1.0.2...4211b09afe43a31a8609ebb3f8ae6fdbba41fadc

## Action Requested

Please respond LGTM or REJECT (with reasoning).

**Comment by Two-Hearts** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
Closed this issue as [v1.0.3](https://github.com/notaryproject/notation-core-go/releases/tag/v1.0.3) has been released.
