### ISSUE TITLE
Refactor code to support multiple envelopes

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-core-go#24]
The package `signer` is tightly coupled with JWS signature envelope. To support other signature envelopes (e.g. COSE) in the future, we need to decouple the logic in the package `signer` at least into the following sub packages:

- `jws`: Process the `SignRequest` and generate JWS signature envelope. Parse and verify JWS signature envelope.
- `cose`: Process the `SignRequest` and generate COSE signature envelope. Parse and verify COSE signature envelope.
- `envelope`: Common logic on processing all kinds of envelopes (e.g. JWS, COSE).

Proposals can be found at

- https://github.com/notaryproject/notation/discussions/278

**Comment by FeynmanZhou** [comment]
Hi @shizhMSFT and @binbin-li ,

It looks like this proposal will be the prerequisite for implementing [COSE support](https://github.com/notaryproject/notation/issues/163) and achieving a loose-coupled architecture for different envelope support, it is significant to add it to RC.1.

cc @notaryproject/notation-release-managers

**Comment by priteshbandi** [comment]
> The package signer is tightly coupled with JWS signature envelope. To support other signature envelopes (e.g. COSE) in the future, we need to decouple the logic in the package signer at least into the following sub packages:

All the public methods of signer package are not at all coupled with JWS. Its just that signer.go and jws.go happens to exists in same (signer) package.


IMO we can just move jws.go and jwt.go to separate sub package and that should work.

**Comment by shizhMSFT** [comment]
Closing as the code refactoring change has been merged to alpha.4.
