### ISSUE TITLE
CRL fetcher retry on retriable error

### ISSUE THREAD

**Issue by junczhu** [notaryproject/notation-core-go#240]
### Is your feature request related to a problem?

Based on the `fetcher` implementation, I understand that if an error is found, the function immediately returns it to avoid unnecessary fetch attempts for known problematic URLs. 
But would it be beneficial to allow a limited number of retries to make it more robust in cases facing retriable errors?

### What solution do you propose?

probably need to consider only retry on retriable error

### What alternatives have you considered?

NA

**Comment by JeyJeyGao** [comment]
We will not implement this in notation-core-go and will not introduce any retry logic. Please implement your own retriable HTTP client and pass it to the fetcher to enable retries.
