### ISSUE TITLE
Release v0.1.0-alpha.4  for Notation-core-go

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/notation-core-go#85]
Picking a new version of notation-core-go for building Alpha-4 release.

- [x]  Decide on main commit for a release
- [x] Cut branch named v0.1.0-alpha.4 based on agreed upon main commit
- [x] Cut a tag named v0.1.0-alpha.4

@SteveLasker @gokarnm @iamsamirzon @FeynmanZh @vaninrao10

**Comment by dtzar** [comment]
LGTM
