### ISSUE TITLE
Release a new version for Notation-core-go

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation-core-go#90]
Picking a new version of notation-core-go for building v0.2.0-beta.1 release.

- [x]  Decide on main commit for a release
- [x]  Cut branch named v0.2.0-beta.1 based on agreed upon main commit
- [x]  Cut a tag named v0.2.0-beta.1

/cc: @dtzar @iamsamirzon @FeynmanZhou @shizhMSFT @vaninrao10

**Comment by shizhMSFT** [comment]
The version should be `v0.2.0-beta.1` since there are breaking changes introduced on public APIs.

**Comment by yizha1** [comment]
commit: [3033a42](https://github.com/notaryproject/notation-core-go/commit/3033a42e145c38048a2c3e37c0b45133eb0ef148)

**Comment by yizha1** [comment]
Released https://github.com/notaryproject/notation-core-go/releases/tag/v0.2.0-beta.1
