### ISSUE TITLE
Ensure `notation-core-go` works with `go-cose v1.0.0-rc.2`

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation-core-go#92]
`go-cose` will cut a [v1.0.0-rc.2](https://github.com/veraison/go-cose/issues/112) release after resolving https://github.com/veraison/go-cose/issues/110.

We need to make sure that the implementation to https://github.com/veraison/go-cose/issues/110 works with `notation-core-go` before the release cut.

**Comment by patrickzheng200** [comment]
Replaced go-cose with `github.com/qmuntal/go-cose v0.0.0-20221104155458-b2a1e5fadeef ` along with other dependencies accordingly in notation-core-go, notation-go, and notation. Tested both sign and verification from Notation CLI. Works as expected.
