### ISSUE TITLE
Release v1.0.0-rc.1 for notation-core-go

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation-core-go#99]
Release `v1.0.0-rc.1` for `notation-core-go`:

- [x] Decide on main commit for a release: Commit id [3022517](https://github.com/notaryproject/notation-core-go/commit/3022517b84c105067c560c67c30c7551d2231d24)
- [x] Cut branch named `v1.0.0-rc.1` based on agreed upon main commit
- [x] Cut a tag named `v1.0.0-rc.1`

@SteveLasker @NiazFK  Please respond with **+1** comment for approval.

cc: @iamsamirzon  @vaninrao10 @priteshbandi  @toddysm @FeynmanZhou @shizhMSFT

**Comment by shizhMSFT** [comment]
+1

**Comment by SteveLasker** [comment]
+1

**Comment by vaninrao10** [comment]
+1

**Comment by vaninrao10** [comment]
> +1

+1

**Comment by vaninrao10** [comment]
> +1

**Comment by yizha1** [comment]
`notation-core-go` released https://github.com/notaryproject/notation-core-go/releases/tag/v1.0.0-rc.1
